from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_db_helper(object):
    def setupUi(self, db_helper):
        db_helper.setObjectName("db_helper")
        db_helper.setFixedSize(500, 410)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(db_helper.sizePolicy().hasHeightForWidth())
        db_helper.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=db_helper)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 10, 501, 391))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.dbName_lineEdit = QtWidgets.QLineEdit(parent=self.page_1)
        self.dbName_lineEdit.setGeometry(QtCore.QRect(370, 150, 121, 20))
        self.dbName_lineEdit.setObjectName("dbName_lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.page_1)
        self.label_2.setGeometry(QtCore.QRect(140, 130, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.page_1)
        self.label_4.setGeometry(QtCore.QRect(380, 130, 101, 16))
        self.label_4.setObjectName("label_4")
        self.link_lineEdit = QtWidgets.QLineEdit(parent=self.page_1)
        self.link_lineEdit.setGeometry(QtCore.QRect(250, 150, 113, 20))
        self.link_lineEdit.setObjectName("link_lineEdit")
        self.password_lineEdit = QtWidgets.QLineEdit(parent=self.page_1)
        self.password_lineEdit.setGeometry(QtCore.QRect(130, 150, 113, 20))
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.label_3 = QtWidgets.QLabel(parent=self.page_1)
        self.label_3.setGeometry(QtCore.QRect(260, 130, 31, 16))
        self.label_3.setObjectName("label_3")
        self.setConnection_pushButton = QtWidgets.QPushButton(parent=self.page_1)
        self.setConnection_pushButton.setGeometry(QtCore.QRect(8, 180, 481, 41))
        self.setConnection_pushButton.setObjectName("setConnection_pushButton")
        self.login_lineEdit = QtWidgets.QLineEdit(parent=self.page_1)
        self.login_lineEdit.setGeometry(QtCore.QRect(10, 150, 113, 20))
        self.login_lineEdit.setObjectName("login_lineEdit")
        self.label = QtWidgets.QLabel(parent=self.page_1)
        self.label.setGeometry(QtCore.QRect(20, 130, 47, 13))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.users_upperBalanceLimit_lineEdit = QtWidgets.QLineEdit(parent=self.page_2)
        self.users_upperBalanceLimit_lineEdit.setGeometry(QtCore.QRect(152, 160, 161, 20))
        self.users_upperBalanceLimit_lineEdit.setObjectName("users_upperBalanceLimit_lineEdit")
        self.label_8 = QtWidgets.QLabel(parent=self.page_2)
        self.label_8.setGeometry(QtCore.QRect(16, 110, 471, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.transactions_upperTransactedLimit_lineEdit = QtWidgets.QLineEdit(parent=self.page_2)
        self.transactions_upperTransactedLimit_lineEdit.setGeometry(QtCore.QRect(152, 300, 161, 20))
        self.transactions_upperTransactedLimit_lineEdit.setObjectName("transactions_upperTransactedLimit_lineEdit")
        self.label_5 = QtWidgets.QLabel(parent=self.page_2)
        self.label_5.setGeometry(QtCore.QRect(20, 140, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(parent=self.page_2)
        self.label_11.setGeometry(QtCore.QRect(338, 280, 151, 16))
        self.label_11.setObjectName("label_11")
        self.label_6 = QtWidgets.QLabel(parent=self.page_2)
        self.label_6.setGeometry(QtCore.QRect(160, 140, 151, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.page_2)
        self.label_7.setGeometry(QtCore.QRect(338, 140, 151, 16))
        self.label_7.setObjectName("label_7")
        self.label_12 = QtWidgets.QLabel(parent=self.page_2)
        self.label_12.setGeometry(QtCore.QRect(160, 280, 151, 16))
        self.label_12.setObjectName("label_12")
        self.transactions_createEntries_pushButton = QtWidgets.QPushButton(parent=self.page_2)
        self.transactions_createEntries_pushButton.setGeometry(QtCore.QRect(10, 330, 481, 51))
        self.transactions_createEntries_pushButton.setObjectName("transactions_createEntries_pushButton")
        self.dropDatabase_pushButton = QtWidgets.QPushButton(parent=self.page_2)
        self.dropDatabase_pushButton.setGeometry(QtCore.QRect(10, 60, 481, 41))
        self.dropDatabase_pushButton.setObjectName("dropDatabase_pushButton")
        self.label_10 = QtWidgets.QLabel(parent=self.page_2)
        self.label_10.setGeometry(QtCore.QRect(20, 280, 111, 16))
        self.label_10.setObjectName("label_10")
        self.transactions_lowerTransactedLimit_lineEdit = QtWidgets.QLineEdit(parent=self.page_2)
        self.transactions_lowerTransactedLimit_lineEdit.setGeometry(QtCore.QRect(330, 300, 161, 20))
        self.transactions_lowerTransactedLimit_lineEdit.setObjectName("transactions_lowerTransactedLimit_lineEdit")
        self.transactions_entryAmount_lineEdit = QtWidgets.QLineEdit(parent=self.page_2)
        self.transactions_entryAmount_lineEdit.setGeometry(QtCore.QRect(12, 300, 121, 20))
        self.transactions_entryAmount_lineEdit.setObjectName("transactions_entryAmount_lineEdit")
        self.label_9 = QtWidgets.QLabel(parent=self.page_2)
        self.label_9.setGeometry(QtCore.QRect(16, 250, 471, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.users_createEntries_pushButton = QtWidgets.QPushButton(parent=self.page_2)
        self.users_createEntries_pushButton.setGeometry(QtCore.QRect(10, 190, 481, 51))
        self.users_createEntries_pushButton.setObjectName("users_createEntries_pushButton")
        self.users_entryAmount_lineEdit = QtWidgets.QLineEdit(parent=self.page_2)
        self.users_entryAmount_lineEdit.setGeometry(QtCore.QRect(12, 160, 121, 20))
        self.users_entryAmount_lineEdit.setObjectName("users_entryAmount_lineEdit")
        self.createTables_pushButton = QtWidgets.QPushButton(parent=self.page_2)
        self.createTables_pushButton.setGeometry(QtCore.QRect(10, 10, 481, 41))
        self.createTables_pushButton.setObjectName("createTables_pushButton")
        self.users_lowerBalanceLimit_lineEdit = QtWidgets.QLineEdit(parent=self.page_2)
        self.users_lowerBalanceLimit_lineEdit.setGeometry(QtCore.QRect(330, 160, 161, 20))
        self.users_lowerBalanceLimit_lineEdit.setObjectName("users_lowerBalanceLimit_lineEdit")
        self.stackedWidget.addWidget(self.page_2)
        db_helper.setCentralWidget(self.centralwidget)

        self.retranslateUi(db_helper)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(db_helper)

    def retranslateUi(self, db_helper):
        _translate = QtCore.QCoreApplication.translate
        db_helper.setWindowTitle(_translate("db_helper", "DB_Helper"))
        self.label_2.setText(_translate("db_helper", "Password"))
        self.label_4.setText(_translate("db_helper", "Database name"))
        self.label_3.setText(_translate("db_helper", "Link"))
        self.setConnection_pushButton.setText(_translate("db_helper", "Set connection"))
        self.label.setText(_translate("db_helper", "Login"))
        self.label_8.setText(_translate("db_helper", "USERS"))
        self.label_5.setText(_translate("db_helper", "Entry amount"))
        self.label_11.setText(_translate("db_helper", "Lower transacted limit"))
        self.label_6.setText(_translate("db_helper", "Upper balance limit"))
        self.label_7.setText(_translate("db_helper", "Lower balance limit"))
        self.label_12.setText(_translate("db_helper", "Upper transacted limit"))
        self.transactions_createEntries_pushButton.setText(_translate("db_helper", "Create entries"))
        self.dropDatabase_pushButton.setText(_translate("db_helper", "Drop database"))
        self.label_10.setText(_translate("db_helper", "Entry amount"))
        self.label_9.setText(_translate("db_helper", "TRANSACTIONS"))
        self.users_createEntries_pushButton.setText(_translate("db_helper", "Create entries"))
        self.createTables_pushButton.setText(_translate("db_helper", "Create tables"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    db_helper = QtWidgets.QMainWindow()
    ui = Ui_db_helper()
    ui.setupUi(db_helper)
    db_helper.show()
    sys.exit(app.exec())
