from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_db_helper(object):
    def setupUi(self, db_helper):
        db_helper.setObjectName("db_helper")
        db_helper.resize(869, 637)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(db_helper.sizePolicy().hasHeightForWidth())
        db_helper.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=db_helper)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 10, 861, 621))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.dbName_lineEdit = QtWidgets.QLineEdit(parent=self.page_1)
        self.dbName_lineEdit.setGeometry(QtCore.QRect(542, 250, 121, 20))
        self.dbName_lineEdit.setObjectName("dbName_lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.page_1)
        self.label_2.setGeometry(QtCore.QRect(312, 230, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.page_1)
        self.label_4.setGeometry(QtCore.QRect(552, 230, 101, 16))
        self.label_4.setObjectName("label_4")
        self.link_lineEdit = QtWidgets.QLineEdit(parent=self.page_1)
        self.link_lineEdit.setGeometry(QtCore.QRect(422, 250, 113, 20))
        self.link_lineEdit.setObjectName("link_lineEdit")
        self.password_lineEdit = QtWidgets.QLineEdit(parent=self.page_1)
        self.password_lineEdit.setGeometry(QtCore.QRect(302, 250, 113, 20))
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.label_3 = QtWidgets.QLabel(parent=self.page_1)
        self.label_3.setGeometry(QtCore.QRect(432, 230, 31, 16))
        self.label_3.setObjectName("label_3")
        self.setConnection_pushButton = QtWidgets.QPushButton(parent=self.page_1)
        self.setConnection_pushButton.setGeometry(QtCore.QRect(180, 280, 481, 41))
        self.setConnection_pushButton.setObjectName("setConnection_pushButton")
        self.login_lineEdit = QtWidgets.QLineEdit(parent=self.page_1)
        self.login_lineEdit.setGeometry(QtCore.QRect(182, 250, 113, 20))
        self.login_lineEdit.setObjectName("login_lineEdit")
        self.label = QtWidgets.QLabel(parent=self.page_1)
        self.label.setGeometry(QtCore.QRect(190, 230, 47, 13))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.users_upperBalanceLimit_lineEdit = QtWidgets.QLineEdit(parent=self.page_2)
        self.users_upperBalanceLimit_lineEdit.setGeometry(QtCore.QRect(250, 190, 111, 20))
        self.users_upperBalanceLimit_lineEdit.setObjectName("users_upperBalanceLimit_lineEdit")
        self.label_8 = QtWidgets.QLabel(parent=self.page_2)
        self.label_8.setGeometry(QtCore.QRect(20, 140, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.user_ipn_toGeneration_lineEdit = QtWidgets.QLineEdit(parent=self.page_2)
        self.user_ipn_toGeneration_lineEdit.setGeometry(QtCore.QRect(700, 190, 131, 20))
        self.user_ipn_toGeneration_lineEdit.setObjectName("user_ipn_toGeneration_lineEdit")
        self.label_5 = QtWidgets.QLabel(parent=self.page_2)
        self.label_5.setGeometry(QtCore.QRect(20, 170, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(parent=self.page_2)
        self.label_11.setGeometry(QtCore.QRect(550, 170, 51, 16))
        self.label_11.setObjectName("label_11")
        self.label_6 = QtWidgets.QLabel(parent=self.page_2)
        self.label_6.setGeometry(QtCore.QRect(250, 170, 111, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.page_2)
        self.label_7.setGeometry(QtCore.QRect(130, 170, 111, 16))
        self.label_7.setObjectName("label_7")
        self.label_12 = QtWidgets.QLabel(parent=self.page_2)
        self.label_12.setGeometry(QtCore.QRect(710, 170, 51, 16))
        self.label_12.setObjectName("label_12")
        self.transactions_createEntries_pushButton = QtWidgets.QPushButton(parent=self.page_2)
        self.transactions_createEntries_pushButton.setGeometry(QtCore.QRect(380, 260, 461, 41))
        self.transactions_createEntries_pushButton.setObjectName("transactions_createEntries_pushButton")
        self.label_10 = QtWidgets.QLabel(parent=self.page_2)
        self.label_10.setGeometry(QtCore.QRect(390, 170, 111, 16))
        self.label_10.setObjectName("label_10")
        self.user_id_toGeneration_lineEdit = QtWidgets.QLineEdit(parent=self.page_2)
        self.user_id_toGeneration_lineEdit.setGeometry(QtCore.QRect(540, 190, 131, 20))
        self.user_id_toGeneration_lineEdit.setObjectName("user_id_toGeneration_lineEdit")
        self.transactions_entryAmount_lineEdit = QtWidgets.QLineEdit(parent=self.page_2)
        self.transactions_entryAmount_lineEdit.setGeometry(QtCore.QRect(380, 190, 131, 20))
        self.transactions_entryAmount_lineEdit.setObjectName("transactions_entryAmount_lineEdit")
        self.label_9 = QtWidgets.QLabel(parent=self.page_2)
        self.label_9.setGeometry(QtCore.QRect(380, 140, 481, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.users_createEntries_pushButton = QtWidgets.QPushButton(parent=self.page_2)
        self.users_createEntries_pushButton.setGeometry(QtCore.QRect(20, 220, 341, 41))
        self.users_createEntries_pushButton.setObjectName("users_createEntries_pushButton")
        self.users_entryAmount_lineEdit = QtWidgets.QLineEdit(parent=self.page_2)
        self.users_entryAmount_lineEdit.setGeometry(QtCore.QRect(20, 190, 101, 20))
        self.users_entryAmount_lineEdit.setObjectName("users_entryAmount_lineEdit")
        self.users_lowerBalanceLimit_lineEdit = QtWidgets.QLineEdit(parent=self.page_2)
        self.users_lowerBalanceLimit_lineEdit.setGeometry(QtCore.QRect(130, 190, 111, 20))
        self.users_lowerBalanceLimit_lineEdit.setObjectName("users_lowerBalanceLimit_lineEdit")
        self.showAll_users_pushButton = QtWidgets.QPushButton(parent=self.page_2)
        self.showAll_users_pushButton.setGeometry(QtCore.QRect(370, 340, 451, 41))
        self.showAll_users_pushButton.setObjectName("showAll_users_pushButton")
        self.showAll_transactions_pushButton = QtWidgets.QPushButton(parent=self.page_2)
        self.showAll_transactions_pushButton.setGeometry(QtCore.QRect(370, 380, 451, 41))
        self.showAll_transactions_pushButton.setObjectName("showAll_transactions_pushButton")
        self.label_13 = QtWidgets.QLabel(parent=self.page_2)
        self.label_13.setGeometry(QtCore.QRect(620, 170, 21, 16))
        self.label_13.setObjectName("label_13")
        self.oneFile_Json_pushButton = QtWidgets.QPushButton(parent=self.page_2)
        self.oneFile_Json_pushButton.setGeometry(QtCore.QRect(160, 70, 101, 41))
        self.oneFile_Json_pushButton.setObjectName("oneFile_Json_pushButton")
        self.SeparatedFiles_Json_pushButton = QtWidgets.QPushButton(parent=self.page_2)
        self.SeparatedFiles_Json_pushButton.setGeometry(QtCore.QRect(390, 70, 101, 41))
        self.SeparatedFiles_Json_pushButton.setObjectName("SeparatedFiles_Json_pushButton")
        self.oneFile_Yaml_pushButton = QtWidgets.QPushButton(parent=self.page_2)
        self.oneFile_Yaml_pushButton.setGeometry(QtCore.QRect(520, 70, 101, 41))
        self.oneFile_Yaml_pushButton.setObjectName("oneFile_Yaml_pushButton")
        self.SeparatedFiles_Yaml_pushButton = QtWidgets.QPushButton(parent=self.page_2)
        self.SeparatedFiles_Yaml_pushButton.setGeometry(QtCore.QRect(740, 70, 101, 41))
        self.SeparatedFiles_Yaml_pushButton.setObjectName("SeparatedFiles_Yaml_pushButton")
        self.label_14 = QtWidgets.QLabel(parent=self.page_2)
        self.label_14.setGeometry(QtCore.QRect(283, 80, 91, 21))
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.page_2)
        self.label_15.setGeometry(QtCore.QRect(633, 80, 101, 21))
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.listWidget = QtWidgets.QListWidget(parent=self.page_2)
        self.listWidget.setGeometry(QtCore.QRect(370, 510, 471, 101))
        self.listWidget.setObjectName("listWidget")
        self.ShowEverything_pushButton = QtWidgets.QPushButton(parent=self.page_2)
        self.ShowEverything_pushButton.setGeometry(QtCore.QRect(370, 420, 231, 41))
        self.ShowEverything_pushButton.setObjectName("ShowEverything_pushButton")
        self.label_18 = QtWidgets.QLabel(parent=self.page_2)
        self.label_18.setGeometry(QtCore.QRect(610, 420, 51, 16))
        self.label_18.setObjectName("label_18")
        self.user_id_toShowing_lineEdit = QtWidgets.QLineEdit(parent=self.page_2)
        self.user_id_toShowing_lineEdit.setGeometry(QtCore.QRect(610, 440, 111, 20))
        self.user_id_toShowing_lineEdit.setObjectName("user_id_toShowing_lineEdit")
        self.user_ipn_toShowing_lineEdit = QtWidgets.QLineEdit(parent=self.page_2)
        self.user_ipn_toShowing_lineEdit.setGeometry(QtCore.QRect(730, 440, 111, 20))
        self.user_ipn_toShowing_lineEdit.setObjectName("user_ipn_toShowing_lineEdit")
        self.label_16 = QtWidgets.QLabel(parent=self.page_2)
        self.label_16.setGeometry(QtCore.QRect(730, 420, 51, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.page_2)
        self.label_17.setGeometry(QtCore.QRect(683, 420, 21, 16))
        self.label_17.setObjectName("label_17")
        self.CountOfEverything_pushButton = QtWidgets.QPushButton(parent=self.page_2)
        self.CountOfEverything_pushButton.setGeometry(QtCore.QRect(370, 460, 101, 41))
        self.CountOfEverything_pushButton.setObjectName("CountOfEverything_pushButton")
        self.ShowDetailesOfTransaction_pushButton = QtWidgets.QPushButton(parent=self.page_2)
        self.ShowDetailesOfTransaction_pushButton.setGeometry(QtCore.QRect(480, 460, 241, 41))
        self.ShowDetailesOfTransaction_pushButton.setObjectName("ShowDetailesOfTransaction_pushButton")
        self.transcation_id_toShowing_lineEdit = QtWidgets.QLineEdit(parent=self.page_2)
        self.transcation_id_toShowing_lineEdit.setGeometry(QtCore.QRect(730, 480, 111, 20))
        self.transcation_id_toShowing_lineEdit.setObjectName("transcation_id_toShowing_lineEdit")
        self.label_37 = QtWidgets.QLabel(parent=self.page_2)
        self.label_37.setGeometry(QtCore.QRect(730, 460, 111, 16))
        self.label_37.setObjectName("label_37")
        self.groupBox = QtWidgets.QGroupBox(parent=self.page_2)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 141, 121))
        self.groupBox.setObjectName("groupBox")
        self.createTables_pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.createTables_pushButton.setGeometry(QtCore.QRect(10, 20, 121, 41))
        self.createTables_pushButton.setObjectName("createTables_pushButton")
        self.dropDatabase_pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.dropDatabase_pushButton.setGeometry(QtCore.QRect(10, 70, 121, 41))
        self.dropDatabase_pushButton.setObjectName("dropDatabase_pushButton")
        self.label_19 = QtWidgets.QLabel(parent=self.page_2)
        self.label_19.setGeometry(QtCore.QRect(160, 30, 671, 21))
        self.label_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.transactions_timeWindowStart_dateTimeEdit = QtWidgets.QDateTimeEdit(parent=self.page_2)
        self.transactions_timeWindowStart_dateTimeEdit.setGeometry(QtCore.QRect(390, 230, 194, 22))
        self.transactions_timeWindowStart_dateTimeEdit.setDate(QtCore.QDate(2023, 1, 1))
        self.transactions_timeWindowStart_dateTimeEdit.setCalendarPopup(True)
        self.transactions_timeWindowStart_dateTimeEdit.setObjectName("transactions_timeWindowStart_dateTimeEdit")
        self.transactions_timeWindowEnd_dateTimeEdit = QtWidgets.QDateTimeEdit(parent=self.page_2)
        self.transactions_timeWindowEnd_dateTimeEdit.setGeometry(QtCore.QRect(630, 230, 194, 22))
        self.transactions_timeWindowEnd_dateTimeEdit.setDate(QtCore.QDate(2024, 1, 1))
        self.transactions_timeWindowEnd_dateTimeEdit.setCalendarPopup(True)
        self.transactions_timeWindowEnd_dateTimeEdit.setObjectName("transactions_timeWindowEnd_dateTimeEdit")
        self.label_20 = QtWidgets.QLabel(parent=self.page_2)
        self.label_20.setGeometry(QtCore.QRect(400, 210, 111, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(parent=self.page_2)
        self.label_21.setGeometry(QtCore.QRect(640, 210, 111, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(parent=self.page_2)
        self.label_22.setGeometry(QtCore.QRect(360, 310, 481, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.page_2)
        self.label_23.setGeometry(QtCore.QRect(20, 260, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.logs_textBrowser = QtWidgets.QTextBrowser(parent=self.page_2)
        self.logs_textBrowser.setGeometry(QtCore.QRect(10, 290, 351, 321))
        self.logs_textBrowser.setObjectName("logs_textBrowser")
        self.stackedWidget.addWidget(self.page_2)
        db_helper.setCentralWidget(self.centralwidget)

        self.retranslateUi(db_helper)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(db_helper)

    def retranslateUi(self, db_helper):
        _translate = QtCore.QCoreApplication.translate
        db_helper.setWindowTitle(_translate("db_helper", "DB_Helper"))
        self.label_2.setText(_translate("db_helper", "Password"))
        self.label_4.setText(_translate("db_helper", "Database name"))
        self.link_lineEdit.setPlaceholderText(_translate("db_helper", "localhost"))
        self.label_3.setText(_translate("db_helper", "Link"))
        self.setConnection_pushButton.setText(_translate("db_helper", "Set connection"))
        self.login_lineEdit.setPlaceholderText(_translate("db_helper", "postgres"))
        self.label.setText(_translate("db_helper", "Login"))
        self.users_upperBalanceLimit_lineEdit.setPlaceholderText(_translate("db_helper", "50000"))
        self.label_8.setText(_translate("db_helper", "<html><head/><body><p>&lt; - - - - - - USERS - - - - - - &gt;</p></body></html>"))
        self.user_ipn_toGeneration_lineEdit.setPlaceholderText(_translate("db_helper", "optional"))
        self.label_5.setText(_translate("db_helper", "Amount"))
        self.label_11.setText(_translate("db_helper", "User ID"))
        self.label_6.setText(_translate("db_helper", "Max balance"))
        self.label_7.setText(_translate("db_helper", "Min balance"))
        self.label_12.setText(_translate("db_helper", "User IPN"))
        self.transactions_createEntries_pushButton.setText(_translate("db_helper", "Create entries"))
        self.label_10.setText(_translate("db_helper", "Amount"))
        self.user_id_toGeneration_lineEdit.setPlaceholderText(_translate("db_helper", "optional"))
        self.transactions_entryAmount_lineEdit.setPlaceholderText(_translate("db_helper", "0"))
        self.label_9.setText(_translate("db_helper", "<html><head/><body><p>&lt; - - - - - - TRANSACTIONS - - - - - - &gt;</p></body></html>"))
        self.users_createEntries_pushButton.setText(_translate("db_helper", "Create entries"))
        self.users_entryAmount_lineEdit.setPlaceholderText(_translate("db_helper", "0"))
        self.users_lowerBalanceLimit_lineEdit.setPlaceholderText(_translate("db_helper", "1000"))
        self.showAll_users_pushButton.setText(_translate("db_helper", "All users"))
        self.showAll_transactions_pushButton.setText(_translate("db_helper", "All transactions"))
        self.label_13.setText(_translate("db_helper", "or"))
        self.oneFile_Json_pushButton.setText(_translate("db_helper", "One file"))
        self.SeparatedFiles_Json_pushButton.setText(_translate("db_helper", "Different files"))
        self.oneFile_Yaml_pushButton.setText(_translate("db_helper", "One file"))
        self.SeparatedFiles_Yaml_pushButton.setText(_translate("db_helper", "Different files"))
        self.label_14.setText(_translate("db_helper", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">&lt;-JSON-&gt;</span></p></body></html>"))
        self.label_15.setText(_translate("db_helper", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">&lt;-YAML-&gt;</span></p></body></html>"))
        self.ShowEverything_pushButton.setText(_translate("db_helper", "1 User and his transactions ->"))
        self.label_18.setText(_translate("db_helper", "User ID"))
        self.label_16.setText(_translate("db_helper", "User IPN"))
        self.label_17.setText(_translate("db_helper", "or"))
        self.CountOfEverything_pushButton.setText(_translate("db_helper", "DB STATUS"))
        self.ShowDetailesOfTransaction_pushButton.setText(_translate("db_helper", "1 Transaction ->"))
        self.label_37.setText(_translate("db_helper", "Transaction ID"))
        self.groupBox.setTitle(_translate("db_helper", "Begin/end db"))
        self.createTables_pushButton.setText(_translate("db_helper", "Create tables"))
        self.dropDatabase_pushButton.setText(_translate("db_helper", "Drop database"))
        self.label_19.setText(_translate("db_helper", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">&lt; - - - - - - GET ENTRIES (AS FILES) - - - - - - &gt;</span></p></body></html>"))
        self.transactions_timeWindowStart_dateTimeEdit.setDisplayFormat(_translate("db_helper", "dd.MM.yyyy, HH:mm:ss"))
        self.transactions_timeWindowEnd_dateTimeEdit.setDisplayFormat(_translate("db_helper", "dd.MM.yyyy, HH:mm:ss"))
        self.label_20.setText(_translate("db_helper", "Start of timeframe"))
        self.label_21.setText(_translate("db_helper", "End of timeframe"))
        self.label_22.setText(_translate("db_helper", "<html><head/><body><p>&lt; - - - - - - GET ENTRIES (IN-APP) - - - - - - &gt;</p></body></html>"))
        self.label_23.setText(_translate("db_helper", "<html><head/><body><p>&lt; - - - - - - LOGS - - - - - - &gt;</p></body></html>"))
